import type {
  TaggedBranch,
  TaggedFamily,
  TaggedValuesModel,
} from "../../compiler/tagged-values.ts";
import type { OutputFile } from "../../index.ts";

function completeForm(family: TaggedFamily, branch: TaggedBranch): string {
  return branch.payload === undefined
    ? `${family.name}.${branch.name}`
    : `${family.name}.${branch.name}(${branch.payload.name})`;
}

function emitBranchType(lines: string[], family: TaggedFamily, branch: TaggedBranch): void {
  const declaration = branch.publicInput ? "export type" : "type";
  lines.push(
    "",
    `/** Supplies the complete \`${completeForm(family, branch)}\` input form. */`,
    `${declaration} ${branch.typeName} = {`,
    `  /** Selects the ${branch.name} branch. */ ${family.tagField}: typeof ${family.numericFamily.name}.${branch.name};`,
  );
  if (branch.payload !== undefined) {
    lines.push(
      `  /** Supplies the numeric payload for \`${completeForm(family, branch)}\`. */ ${branch.payload.name}: number;`,
    );
  }
  lines.push("};");
}

function emitUnionType(lines: string[], name: string, members: readonly string[]): void {
  const declaration = `export type ${name} = ${members.join(" | ")};`;
  if (declaration.length <= 100) {
    lines.push(declaration);
    return;
  }
  lines.push(`export type ${name} =`, ...members.map((member) => `  | ${member}`));
  lines[lines.length - 1] += ";";
}

function emitAliases(lines: string[], family: TaggedFamily): void {
  const shorthand = family.numberShorthand;
  for (const alias of family.publicAliases) {
    const branchTypes = alias.branches.map((branch) => branch.typeName);
    const inputTypes = alias.acceptsNumber ? ["number", ...branchTypes] : branchTypes;
    const outputTypes = branchTypes.map((typeName) => `Readonly<${typeName}>`);
    lines.push("");
    if (alias.acceptsNumber && shorthand !== undefined) {
      lines.push(
        `/** Accepts a number as shorthand for \`${completeForm(family, shorthand.targetBranch)}\`, or a complete tagged \`${alias.inputName}\` value. */`,
      );
    } else {
      lines.push(`/** Supplies a complete tagged \`${alias.inputName}\` value. */`);
    }
    emitUnionType(lines, alias.inputName, inputTypes);
    lines.push("");
    lines.push(
      `/** Represents a complete tagged \`${alias.outputName}\` value returned by the binding. */`,
    );
    emitUnionType(lines, alias.outputName, outputTypes);
  }
}

function emitHelper(lines: string[], family: TaggedFamily): void {
  for (const branch of family.branches) {
    if (branch.payload === undefined) {
      lines.push(
        "",
        `const ${family.camelName}${branch.name} = Object.freeze({ ${family.tagField}: ${family.numericFamily.name}.${branch.name} } as const);`,
      );
    }
  }

  const shorthand = family.numberShorthand;
  lines.push("");
  if (shorthand === undefined) {
    lines.push(`/** Provides complete tagged forms for ${family.label} inputs. */`);
  } else {
    lines.push(
      `/** Provides complete tagged forms for ${family.label} inputs, including \`${completeForm(family, shorthand.targetBranch)}\`, the form represented by numeric shorthand. */`,
    );
  }
  lines.push(`export const ${family.name} = Object.freeze({`);
  for (const branch of family.branches) {
    if (branch.payload === undefined) {
      lines.push(`  ${branch.name}: ${family.camelName}${branch.name},`);
    } else {
      lines.push(
        `  ${branch.name}(${branch.payload.name}: number): ${branch.typeName} {`,
        `    return { ${family.tagField}: ${family.numericFamily.name}.${branch.name}, ${branch.payload.name} };`,
        "  },",
      );
    }
  }
  lines.push("});");
}

export function emitTaggedValuesTypeScript(model: TaggedValuesModel): OutputFile {
  const numericFamilies = model.families.map((family) => family.numericFamily.name).toSorted();
  const lines = [
    "// Code generated by tools/api-codegen. DO NOT EDIT.",
    "// Sources: api/numeric-families.json, api/tagged-values.json",
    "// Regenerate: vp run codegen",
    "",
    `import { ${numericFamilies.join(", ")} } from "./numeric-families.js";`,
  ];

  for (const family of model.families) {
    for (const branch of family.branches) emitBranchType(lines, family, branch);
    emitAliases(lines, family);
    emitHelper(lines, family);
  }

  return {
    path: "packages/taffyjs-node/src/tagged-values.ts",
    content: lines.join("\n"),
  };
}
