[workspace]
members = ["crates/taffyjs_binding"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.88"

[workspace.dependencies]
napi = { version = "=3.12.0", features = ["napi8"] }
napi-build = "=2.4.0"
napi-derive = "=3.6.2"
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "8d13fdc88468c83f01b13b36fadc0349950c6f51" }

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
