packages:
  - apps/*
  - benchmarks
  - packages/*
  - packages/taffyjs-node/npm/*
  - tests/*

catalogMode: prefer
linkWorkspacePackages: true

catalog:
  "@napi-rs/cli": 3.8.2
  "@types/node": 22.20.0
  tinybench: 2.9.0
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
  vitepress: 2.0.0-alpha.19
  yoga-layout: 3.2.1

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
