packages:
  - apps/*
  - packages/*
  - packages/taffyjs-node/npm/*
  - tests/*

catalogMode: prefer
linkWorkspacePackages: true

catalog:
  "@napi-rs/cli": 3.8.2
  "@types/node": 22.18.0
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
  vitepress: 2.0.0-alpha.19
  vue: ^3.5.41

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
