// Generated by tools/generate-numeric-families.mjs. Do not edit.

import {
  Display,
  type Display as DisplayValue,
  BoxSizing,
  type BoxSizing as BoxSizingValue,
  Direction,
  type Direction as DirectionValue,
  Overflow,
  type Overflow as OverflowValue,
  Float,
  type Float as FloatValue,
  Clear,
  type Clear as ClearValue,
  Position,
  type Position as PositionValue,
  TextAlign,
  type TextAlign as TextAlignValue,
  FlexDirection,
  type FlexDirection as FlexDirectionValue,
  FlexWrap,
  type FlexWrap as FlexWrapValue,
  GridAutoFlow,
  type GridAutoFlow as GridAutoFlowValue,
  AlignItems,
  type AlignItems as AlignItemsValue,
  AlignContent,
  type AlignContent as AlignContentValue,
  LengthUnit,
  type LengthUnit as LengthUnitValue,
  AvailableSpaceKind,
  type AvailableSpaceKind as AvailableSpaceKindValue,
  GridPlacementKind,
  type GridPlacementKind as GridPlacementKindValue,
  TrackSizingKind,
  type TrackSizingKind as TrackSizingKindValue,
  RepetitionCountKind,
  type RepetitionCountKind as RepetitionCountKindValue,
  GridTemplateComponentKind,
  type GridTemplateComponentKind as GridTemplateComponentKindValue,
  DetailedLayoutInfoKind,
  type DetailedLayoutInfoKind as DetailedLayoutInfoKindValue,
} from "@taffyjs/node";

function narrowDisplay(value: DisplayValue): void {
  switch (value) {
    case Display.Block: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case Display.FlowRoot: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case Display.Flex: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case Display.Grid: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
    case Display.None: {
      const narrowed: 4 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowDisplay;

function narrowBoxSizing(value: BoxSizingValue): void {
  switch (value) {
    case BoxSizing.BorderBox: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case BoxSizing.ContentBox: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowBoxSizing;

function narrowDirection(value: DirectionValue): void {
  switch (value) {
    case Direction.Ltr: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case Direction.Rtl: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowDirection;

function narrowOverflow(value: OverflowValue): void {
  switch (value) {
    case Overflow.Visible: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case Overflow.Clip: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case Overflow.Hidden: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case Overflow.Scroll: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowOverflow;

function narrowFloat(value: FloatValue): void {
  switch (value) {
    case Float.Left: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case Float.Right: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case Float.None: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowFloat;

function narrowClear(value: ClearValue): void {
  switch (value) {
    case Clear.Left: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case Clear.Right: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case Clear.Both: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case Clear.None: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowClear;

function narrowPosition(value: PositionValue): void {
  switch (value) {
    case Position.Relative: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case Position.Absolute: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowPosition;

function narrowTextAlign(value: TextAlignValue): void {
  switch (value) {
    case TextAlign.Auto: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case TextAlign.LegacyLeft: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case TextAlign.LegacyRight: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case TextAlign.LegacyCenter: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowTextAlign;

function narrowFlexDirection(value: FlexDirectionValue): void {
  switch (value) {
    case FlexDirection.Row: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case FlexDirection.Column: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case FlexDirection.RowReverse: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case FlexDirection.ColumnReverse: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowFlexDirection;

function narrowFlexWrap(value: FlexWrapValue): void {
  switch (value) {
    case FlexWrap.NoWrap: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case FlexWrap.Wrap: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case FlexWrap.WrapReverse: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowFlexWrap;

function narrowGridAutoFlow(value: GridAutoFlowValue): void {
  switch (value) {
    case GridAutoFlow.Row: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case GridAutoFlow.Column: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case GridAutoFlow.RowDense: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case GridAutoFlow.ColumnDense: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowGridAutoFlow;

function narrowAlignItems(value: AlignItemsValue): void {
  switch (value) {
    case AlignItems.Start: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case AlignItems.End: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case AlignItems.FlexStart: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case AlignItems.FlexEnd: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
    case AlignItems.SelfStart: {
      const narrowed: 4 = value;
      void narrowed;
      return;
    }
    case AlignItems.SelfEnd: {
      const narrowed: 5 = value;
      void narrowed;
      return;
    }
    case AlignItems.Center: {
      const narrowed: 6 = value;
      void narrowed;
      return;
    }
    case AlignItems.Baseline: {
      const narrowed: 7 = value;
      void narrowed;
      return;
    }
    case AlignItems.Stretch: {
      const narrowed: 8 = value;
      void narrowed;
      return;
    }
    case AlignItems.SafeStart: {
      const narrowed: 9 = value;
      void narrowed;
      return;
    }
    case AlignItems.SafeEnd: {
      const narrowed: 10 = value;
      void narrowed;
      return;
    }
    case AlignItems.SafeFlexStart: {
      const narrowed: 11 = value;
      void narrowed;
      return;
    }
    case AlignItems.SafeFlexEnd: {
      const narrowed: 12 = value;
      void narrowed;
      return;
    }
    case AlignItems.SafeSelfStart: {
      const narrowed: 13 = value;
      void narrowed;
      return;
    }
    case AlignItems.SafeSelfEnd: {
      const narrowed: 14 = value;
      void narrowed;
      return;
    }
    case AlignItems.SafeCenter: {
      const narrowed: 15 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowAlignItems;

function narrowAlignContent(value: AlignContentValue): void {
  switch (value) {
    case AlignContent.Start: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case AlignContent.End: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case AlignContent.FlexStart: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case AlignContent.FlexEnd: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
    case AlignContent.Center: {
      const narrowed: 4 = value;
      void narrowed;
      return;
    }
    case AlignContent.Stretch: {
      const narrowed: 5 = value;
      void narrowed;
      return;
    }
    case AlignContent.SpaceBetween: {
      const narrowed: 6 = value;
      void narrowed;
      return;
    }
    case AlignContent.SpaceEvenly: {
      const narrowed: 7 = value;
      void narrowed;
      return;
    }
    case AlignContent.SpaceAround: {
      const narrowed: 8 = value;
      void narrowed;
      return;
    }
    case AlignContent.SafeStart: {
      const narrowed: 9 = value;
      void narrowed;
      return;
    }
    case AlignContent.SafeEnd: {
      const narrowed: 10 = value;
      void narrowed;
      return;
    }
    case AlignContent.SafeFlexStart: {
      const narrowed: 11 = value;
      void narrowed;
      return;
    }
    case AlignContent.SafeFlexEnd: {
      const narrowed: 12 = value;
      void narrowed;
      return;
    }
    case AlignContent.SafeCenter: {
      const narrowed: 13 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowAlignContent;

function narrowLengthUnit(value: LengthUnitValue): void {
  switch (value) {
    case LengthUnit.Length: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case LengthUnit.Percent: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case LengthUnit.Auto: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowLengthUnit;

function narrowAvailableSpaceKind(value: AvailableSpaceKindValue): void {
  switch (value) {
    case AvailableSpaceKind.Definite: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case AvailableSpaceKind.MinContent: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case AvailableSpaceKind.MaxContent: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowAvailableSpaceKind;

function narrowGridPlacementKind(value: GridPlacementKindValue): void {
  switch (value) {
    case GridPlacementKind.Auto: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case GridPlacementKind.Line: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case GridPlacementKind.NamedLine: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case GridPlacementKind.Span: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
    case GridPlacementKind.NamedSpan: {
      const narrowed: 4 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowGridPlacementKind;

function narrowTrackSizingKind(value: TrackSizingKindValue): void {
  switch (value) {
    case TrackSizingKind.Length: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case TrackSizingKind.Percent: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case TrackSizingKind.Auto: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
    case TrackSizingKind.MinContent: {
      const narrowed: 3 = value;
      void narrowed;
      return;
    }
    case TrackSizingKind.MaxContent: {
      const narrowed: 4 = value;
      void narrowed;
      return;
    }
    case TrackSizingKind.FitContent: {
      const narrowed: 5 = value;
      void narrowed;
      return;
    }
    case TrackSizingKind.Fr: {
      const narrowed: 6 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowTrackSizingKind;

function narrowRepetitionCountKind(value: RepetitionCountKindValue): void {
  switch (value) {
    case RepetitionCountKind.Count: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case RepetitionCountKind.AutoFill: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
    case RepetitionCountKind.AutoFit: {
      const narrowed: 2 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowRepetitionCountKind;

function narrowGridTemplateComponentKind(value: GridTemplateComponentKindValue): void {
  switch (value) {
    case GridTemplateComponentKind.Single: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case GridTemplateComponentKind.Repeat: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowGridTemplateComponentKind;

function narrowDetailedLayoutInfoKind(value: DetailedLayoutInfoKindValue): void {
  switch (value) {
    case DetailedLayoutInfoKind.None: {
      const narrowed: 0 = value;
      void narrowed;
      return;
    }
    case DetailedLayoutInfoKind.Grid: {
      const narrowed: 1 = value;
      void narrowed;
      return;
    }
  }
  value satisfies never;
}

void narrowDetailedLayoutInfoKind;
