// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/layout-codec.json
// Regenerate: vp run codegen

import type { Point, Rect, Size } from "./public-types.js";

/** Returns a detached readonly snapshot of a node's most recently stored layout. */
export interface Layout {
  /** Reports this node's stable traversal order in the stored layout. */ readonly order: number;
  /** Reports this node's position relative to its parent. */ readonly location: Point<number>;
  /** Reports this node's outer width and height. */ readonly size: Size<number>;
  /** Reports the width and height of this node's content. */ readonly contentSize: Size<number>;
  /** Reports the width and height reserved for scrollbars. */ readonly scrollbarSize: Size<number>;
  /** Reports this node's resolved border widths. */ readonly border: Rect<number>;
  /** Reports this node's resolved padding widths. */ readonly padding: Rect<number>;
  /** Reports this node's resolved margins. */ readonly margin: Rect<number>;
}

const ORDER_SLOT = 0;
const LOCATION_X_SLOT = 1;
const LOCATION_Y_SLOT = 2;
const SIZE_WIDTH_SLOT = 3;
const SIZE_HEIGHT_SLOT = 4;
const CONTENT_SIZE_WIDTH_SLOT = 5;
const CONTENT_SIZE_HEIGHT_SLOT = 6;
const SCROLLBAR_SIZE_WIDTH_SLOT = 7;
const SCROLLBAR_SIZE_HEIGHT_SLOT = 8;
const BORDER_LEFT_SLOT = 9;
const BORDER_RIGHT_SLOT = 10;
const BORDER_TOP_SLOT = 11;
const BORDER_BOTTOM_SLOT = 12;
const PADDING_LEFT_SLOT = 13;
const PADDING_RIGHT_SLOT = 14;
const PADDING_TOP_SLOT = 15;
const PADDING_BOTTOM_SLOT = 16;
const MARGIN_LEFT_SLOT = 17;
const MARGIN_RIGHT_SLOT = 18;
const MARGIN_TOP_SLOT = 19;
const MARGIN_BOTTOM_SLOT = 20;

export const layoutCodecLength = 21;
export const layoutCodecByteLength = 168;

export function decodeLayout(output: Float64Array): Layout {
  return {
    order: output[ORDER_SLOT],
    location: {
      x: output[LOCATION_X_SLOT],
      y: output[LOCATION_Y_SLOT],
    },
    size: {
      width: output[SIZE_WIDTH_SLOT],
      height: output[SIZE_HEIGHT_SLOT],
    },
    contentSize: {
      width: output[CONTENT_SIZE_WIDTH_SLOT],
      height: output[CONTENT_SIZE_HEIGHT_SLOT],
    },
    scrollbarSize: {
      width: output[SCROLLBAR_SIZE_WIDTH_SLOT],
      height: output[SCROLLBAR_SIZE_HEIGHT_SLOT],
    },
    border: {
      left: output[BORDER_LEFT_SLOT],
      right: output[BORDER_RIGHT_SLOT],
      top: output[BORDER_TOP_SLOT],
      bottom: output[BORDER_BOTTOM_SLOT],
    },
    padding: {
      left: output[PADDING_LEFT_SLOT],
      right: output[PADDING_RIGHT_SLOT],
      top: output[PADDING_TOP_SLOT],
      bottom: output[PADDING_BOTTOM_SLOT],
    },
    margin: {
      left: output[MARGIN_LEFT_SLOT],
      right: output[MARGIN_RIGHT_SLOT],
      top: output[MARGIN_TOP_SLOT],
      bottom: output[MARGIN_BOTTOM_SLOT],
    },
  };
}
