// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/numeric-families.json
// Regenerate: vp run codegen

/** Numeric constants shared by public JavaScript values and the native conversion layer. */
export type EnumValue<Family extends Readonly<Record<string, number>>> = Family[keyof Family];

/** Lists the supported display choices as stable numeric constants. */
export const Display = Object.freeze({
  /** Selects the Block choice from the Display numeric family. */
  Block: 0,
  /** Selects the FlowRoot choice from the Display numeric family. */
  FlowRoot: 1,
  /** Selects the Flex choice from the Display numeric family. */
  Flex: 2,
  /** Selects the Grid choice from the Display numeric family. */
  Grid: 3,
  /** Selects the None choice from the Display numeric family. */
  None: 4,
} as const);

export type Display = EnumValue<typeof Display>;

/** Lists the supported box sizing choices as stable numeric constants. */
export const BoxSizing = Object.freeze({
  /** Selects the BorderBox choice from the BoxSizing numeric family. */
  BorderBox: 0,
  /** Selects the ContentBox choice from the BoxSizing numeric family. */
  ContentBox: 1,
} as const);

export type BoxSizing = EnumValue<typeof BoxSizing>;

/** Lists the supported direction choices as stable numeric constants. */
export const Direction = Object.freeze({
  /** Selects the Ltr choice from the Direction numeric family. */
  Ltr: 0,
  /** Selects the Rtl choice from the Direction numeric family. */
  Rtl: 1,
} as const);

export type Direction = EnumValue<typeof Direction>;

/** Lists the supported overflow choices as stable numeric constants. */
export const Overflow = Object.freeze({
  /** Selects the Visible choice from the Overflow numeric family. */
  Visible: 0,
  /** Selects the Clip choice from the Overflow numeric family. */
  Clip: 1,
  /** Selects the Hidden choice from the Overflow numeric family. */
  Hidden: 2,
  /** Selects the Scroll choice from the Overflow numeric family. */
  Scroll: 3,
} as const);

export type Overflow = EnumValue<typeof Overflow>;

/** Lists the supported contain choices as stable numeric constants. */
export const Contain = Object.freeze({
  /** Selects the None choice from the Contain numeric family. */
  None: 0,
  /** Selects the Layout choice from the Contain numeric family. */
  Layout: 1,
  /** Selects the Paint choice from the Contain numeric family. */
  Paint: 2,
  /** Selects the Content choice from the Contain numeric family. */
  Content: 3,
} as const);

export type Contain = EnumValue<typeof Contain>;

/** Lists the supported float choices as stable numeric constants. */
export const Float = Object.freeze({
  /** Selects the Left choice from the Float numeric family. */
  Left: 0,
  /** Selects the Right choice from the Float numeric family. */
  Right: 1,
  /** Selects the None choice from the Float numeric family. */
  None: 2,
} as const);

export type Float = EnumValue<typeof Float>;

/** Lists the supported clear choices as stable numeric constants. */
export const Clear = Object.freeze({
  /** Selects the Left choice from the Clear numeric family. */
  Left: 0,
  /** Selects the Right choice from the Clear numeric family. */
  Right: 1,
  /** Selects the Both choice from the Clear numeric family. */
  Both: 2,
  /** Selects the None choice from the Clear numeric family. */
  None: 3,
} as const);

export type Clear = EnumValue<typeof Clear>;

/** Lists the supported position choices as stable numeric constants. */
export const Position = Object.freeze({
  /** Selects the Relative choice from the Position numeric family. */
  Relative: 0,
  /** Selects the Absolute choice from the Position numeric family. */
  Absolute: 1,
} as const);

export type Position = EnumValue<typeof Position>;

/** Lists the supported text align choices as stable numeric constants. */
export const TextAlign = Object.freeze({
  /** Selects the Auto choice from the TextAlign numeric family. */
  Auto: 0,
  /** Selects the LegacyLeft choice from the TextAlign numeric family. */
  LegacyLeft: 1,
  /** Selects the LegacyRight choice from the TextAlign numeric family. */
  LegacyRight: 2,
  /** Selects the LegacyCenter choice from the TextAlign numeric family. */
  LegacyCenter: 3,
} as const);

export type TextAlign = EnumValue<typeof TextAlign>;

/** Lists the supported flex direction choices as stable numeric constants. */
export const FlexDirection = Object.freeze({
  /** Selects the Row choice from the FlexDirection numeric family. */
  Row: 0,
  /** Selects the Column choice from the FlexDirection numeric family. */
  Column: 1,
  /** Selects the RowReverse choice from the FlexDirection numeric family. */
  RowReverse: 2,
  /** Selects the ColumnReverse choice from the FlexDirection numeric family. */
  ColumnReverse: 3,
} as const);

export type FlexDirection = EnumValue<typeof FlexDirection>;

/** Lists the supported flex wrap choices as stable numeric constants. */
export const FlexWrap = Object.freeze({
  /** Selects the NoWrap choice from the FlexWrap numeric family. */
  NoWrap: 0,
  /** Selects the Wrap choice from the FlexWrap numeric family. */
  Wrap: 1,
  /** Selects the WrapReverse choice from the FlexWrap numeric family. */
  WrapReverse: 2,
} as const);

export type FlexWrap = EnumValue<typeof FlexWrap>;

/** Lists the supported grid auto flow choices as stable numeric constants. */
export const GridAutoFlow = Object.freeze({
  /** Selects the Row choice from the GridAutoFlow numeric family. */
  Row: 0,
  /** Selects the Column choice from the GridAutoFlow numeric family. */
  Column: 1,
  /** Selects the RowDense choice from the GridAutoFlow numeric family. */
  RowDense: 2,
  /** Selects the ColumnDense choice from the GridAutoFlow numeric family. */
  ColumnDense: 3,
} as const);

export type GridAutoFlow = EnumValue<typeof GridAutoFlow>;

/** Lists the supported align items choices as stable numeric constants. */
export const AlignItems = Object.freeze({
  /** Selects the Start choice from the AlignItems numeric family. */
  Start: 0,
  /** Selects the End choice from the AlignItems numeric family. */
  End: 1,
  /** Selects the FlexStart choice from the AlignItems numeric family. */
  FlexStart: 2,
  /** Selects the FlexEnd choice from the AlignItems numeric family. */
  FlexEnd: 3,
  /** Selects the SelfStart choice from the AlignItems numeric family. */
  SelfStart: 4,
  /** Selects the SelfEnd choice from the AlignItems numeric family. */
  SelfEnd: 5,
  /** Selects the Center choice from the AlignItems numeric family. */
  Center: 6,
  /** Selects the Baseline choice from the AlignItems numeric family. */
  Baseline: 7,
  /** Selects the Stretch choice from the AlignItems numeric family. */
  Stretch: 8,
  /** Selects the SafeStart choice from the AlignItems numeric family. */
  SafeStart: 9,
  /** Selects the SafeEnd choice from the AlignItems numeric family. */
  SafeEnd: 10,
  /** Selects the SafeFlexStart choice from the AlignItems numeric family. */
  SafeFlexStart: 11,
  /** Selects the SafeFlexEnd choice from the AlignItems numeric family. */
  SafeFlexEnd: 12,
  /** Selects the SafeSelfStart choice from the AlignItems numeric family. */
  SafeSelfStart: 13,
  /** Selects the SafeSelfEnd choice from the AlignItems numeric family. */
  SafeSelfEnd: 14,
  /** Selects the SafeCenter choice from the AlignItems numeric family. */
  SafeCenter: 15,
} as const);

export type AlignItems = EnumValue<typeof AlignItems>;

/** Lists the supported align content choices as stable numeric constants. */
export const AlignContent = Object.freeze({
  /** Selects the Start choice from the AlignContent numeric family. */
  Start: 0,
  /** Selects the End choice from the AlignContent numeric family. */
  End: 1,
  /** Selects the FlexStart choice from the AlignContent numeric family. */
  FlexStart: 2,
  /** Selects the FlexEnd choice from the AlignContent numeric family. */
  FlexEnd: 3,
  /** Selects the Center choice from the AlignContent numeric family. */
  Center: 4,
  /** Selects the Stretch choice from the AlignContent numeric family. */
  Stretch: 5,
  /** Selects the SpaceBetween choice from the AlignContent numeric family. */
  SpaceBetween: 6,
  /** Selects the SpaceEvenly choice from the AlignContent numeric family. */
  SpaceEvenly: 7,
  /** Selects the SpaceAround choice from the AlignContent numeric family. */
  SpaceAround: 8,
  /** Selects the SafeStart choice from the AlignContent numeric family. */
  SafeStart: 9,
  /** Selects the SafeEnd choice from the AlignContent numeric family. */
  SafeEnd: 10,
  /** Selects the SafeFlexStart choice from the AlignContent numeric family. */
  SafeFlexStart: 11,
  /** Selects the SafeFlexEnd choice from the AlignContent numeric family. */
  SafeFlexEnd: 12,
  /** Selects the SafeCenter choice from the AlignContent numeric family. */
  SafeCenter: 13,
} as const);

export type AlignContent = EnumValue<typeof AlignContent>;

/** Lists the supported length unit choices as stable numeric constants. */
export const LengthUnit = Object.freeze({
  /** Selects the Length choice from the LengthUnit numeric family. */
  Length: 0,
  /** Selects the Percent choice from the LengthUnit numeric family. */
  Percent: 1,
  /** Selects the Auto choice from the LengthUnit numeric family. */
  Auto: 2,
} as const);

export type LengthUnit = EnumValue<typeof LengthUnit>;

/** Lists the supported available space kind choices as stable numeric constants. */
export const AvailableSpaceKind = Object.freeze({
  /** Selects the Definite choice from the AvailableSpaceKind numeric family. */
  Definite: 0,
  /** Selects the MinContent choice from the AvailableSpaceKind numeric family. */
  MinContent: 1,
  /** Selects the MaxContent choice from the AvailableSpaceKind numeric family. */
  MaxContent: 2,
} as const);

export type AvailableSpaceKind = EnumValue<typeof AvailableSpaceKind>;

/** Lists the supported grid placement kind choices as stable numeric constants. */
export const GridPlacementKind = Object.freeze({
  /** Selects the Auto choice from the GridPlacementKind numeric family. */
  Auto: 0,
  /** Selects the Line choice from the GridPlacementKind numeric family. */
  Line: 1,
  /** Selects the NamedLine choice from the GridPlacementKind numeric family. */
  NamedLine: 2,
  /** Selects the Span choice from the GridPlacementKind numeric family. */
  Span: 3,
  /** Selects the NamedSpan choice from the GridPlacementKind numeric family. */
  NamedSpan: 4,
} as const);

export type GridPlacementKind = EnumValue<typeof GridPlacementKind>;

/** Lists the supported track sizing kind choices as stable numeric constants. */
export const TrackSizingKind = Object.freeze({
  /** Selects the Length choice from the TrackSizingKind numeric family. */
  Length: 0,
  /** Selects the Percent choice from the TrackSizingKind numeric family. */
  Percent: 1,
  /** Selects the Auto choice from the TrackSizingKind numeric family. */
  Auto: 2,
  /** Selects the MinContent choice from the TrackSizingKind numeric family. */
  MinContent: 3,
  /** Selects the MaxContent choice from the TrackSizingKind numeric family. */
  MaxContent: 4,
  /** Selects the FitContent choice from the TrackSizingKind numeric family. */
  FitContent: 5,
  /** Selects the Fr choice from the TrackSizingKind numeric family. */
  Fr: 6,
} as const);

export type TrackSizingKind = EnumValue<typeof TrackSizingKind>;

/** Lists the supported repetition count kind choices as stable numeric constants. */
export const RepetitionCountKind = Object.freeze({
  /** Selects the Count choice from the RepetitionCountKind numeric family. */
  Count: 0,
  /** Selects the AutoFill choice from the RepetitionCountKind numeric family. */
  AutoFill: 1,
  /** Selects the AutoFit choice from the RepetitionCountKind numeric family. */
  AutoFit: 2,
} as const);

export type RepetitionCountKind = EnumValue<typeof RepetitionCountKind>;

/** Lists the supported grid template component kind choices as stable numeric constants. */
export const GridTemplateComponentKind = Object.freeze({
  /** Selects the Single choice from the GridTemplateComponentKind numeric family. */
  Single: 0,
  /** Selects the Repeat choice from the GridTemplateComponentKind numeric family. */
  Repeat: 1,
} as const);

export type GridTemplateComponentKind = EnumValue<typeof GridTemplateComponentKind>;

/** Lists the supported detailed layout info kind choices as stable numeric constants. */
export const DetailedLayoutInfoKind = Object.freeze({
  /** Selects the None choice from the DetailedLayoutInfoKind numeric family. */
  None: 0,
  /** Selects the Grid choice from the DetailedLayoutInfoKind numeric family. */
  Grid: 1,
} as const);

export type DetailedLayoutInfoKind = EnumValue<typeof DetailedLayoutInfoKind>;
