// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/numeric-families.json, api/style-codec.json
// Regenerate: vp run codegen

import type {
  AlignContent,
  AlignItems,
  BoxSizing,
  Clear,
  Contain,
  Direction,
  Display,
  FlexDirection,
  FlexWrap,
  Float,
  GridAutoFlow,
  Overflow,
  Position,
  TextAlign,
} from "./numeric-families.js";
import type {
  GridPlacementInput,
  GridTemplateAreasInput,
  GridTemplateComponentInput,
  PartialLineInput,
  PartialPointInput,
  PartialRectInput,
  PartialSizeInput,
  TrackSizingFunctionInput,
} from "./public-types.js";
import type {
  DimensionInput,
  LengthPercentageAutoInput,
  LengthPercentageInput,
} from "./tagged-values.js";
import { withStyleEncoder } from "./style-codec.js";

/** Supplies style fields; creation and setStyle use defaults for omitted fields. */
export interface StyleInput {
  /** Supplies the node's display style when present. */ display?: Display | undefined;
  /** Supplies the node's item is table style when present. */ itemIsTable?: boolean | undefined;
  /** Supplies the node's item is replaced style when present. */ itemIsReplaced?:
    | boolean
    | undefined;
  /** Supplies the node's box sizing style when present. */ boxSizing?: BoxSizing | undefined;
  /** Supplies the node's direction style when present. */ direction?: Direction | undefined;
  /** Supplies the node's overflow style when present. */ overflow?:
    | PartialPointInput<Overflow>
    | undefined;
  /** Supplies the node's scrollbar width style when present. */ scrollbarWidth?:
    | number
    | undefined;
  /** Supplies the node's layout and paint containment style when present. */ contain?:
    | Contain
    | undefined;
  /** Supplies the node's float style when present. */ float?: Float | undefined;
  /** Sets which preceding floats this node must clear. */ clear?: Clear | undefined;
  /** Supplies the node's position style when present. */ position?: Position | undefined;
  /** Supplies the node's inset style when present. */ inset?:
    | LengthPercentageAutoInput
    | PartialRectInput<LengthPercentageAutoInput>
    | undefined;
  /** Supplies the node's size style when present. */ size?:
    | DimensionInput
    | PartialSizeInput<DimensionInput>
    | undefined;
  /** Supplies the node's min size style when present. */ minSize?:
    | DimensionInput
    | PartialSizeInput<DimensionInput>
    | undefined;
  /** Supplies the node's max size style when present. */ maxSize?:
    | DimensionInput
    | PartialSizeInput<DimensionInput>
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ aspectRatio?:
    | number
    | null
    | undefined;
  /** Supplies the node's margin style when present. */ margin?:
    | LengthPercentageAutoInput
    | PartialRectInput<LengthPercentageAutoInput>
    | undefined;
  /** Supplies the node's padding style when present. */ padding?:
    | LengthPercentageInput
    | PartialRectInput<LengthPercentageInput>
    | undefined;
  /** Supplies the node's border style when present. */ border?:
    | LengthPercentageInput
    | PartialRectInput<LengthPercentageInput>
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ alignItems?:
    | AlignItems
    | null
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ alignSelf?:
    | AlignItems
    | null
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ justifyItems?:
    | AlignItems
    | null
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ justifySelf?:
    | AlignItems
    | null
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ alignContent?:
    | AlignContent
    | null
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ justifyContent?:
    | AlignContent
    | null
    | undefined;
  /** Supplies the node's gap style when present. */ gap?:
    | LengthPercentageInput
    | PartialSizeInput<LengthPercentageInput>
    | undefined;
  /** Supplies the node's text align style when present. */ textAlign?: TextAlign | undefined;
  /** Supplies the node's flex direction style when present. */ flexDirection?:
    | FlexDirection
    | undefined;
  /** Supplies the node's flex wrap style when present. */ flexWrap?: FlexWrap | undefined;
  /** Supplies the node's flex basis style when present. */ flexBasis?: DimensionInput | undefined;
  /** Supplies the node's flex grow style when present. */ flexGrow?: number | undefined;
  /** Supplies the node's flex shrink style when present. */ flexShrink?: number | undefined;
  /** Supplies the complete Grid template row list when present. */ gridTemplateRows?:
    | readonly GridTemplateComponentInput[]
    | undefined;
  /** Supplies the complete Grid template column list when present. */ gridTemplateColumns?:
    | readonly GridTemplateComponentInput[]
    | undefined;
  /** Supplies the complete automatic Grid row list when present. */ gridAutoRows?:
    | readonly TrackSizingFunctionInput[]
    | undefined;
  /** Supplies the complete automatic Grid column list when present. */ gridAutoColumns?:
    | readonly TrackSizingFunctionInput[]
    | undefined;
  /** Supplies the node's Grid auto flow style when present. */ gridAutoFlow?:
    | GridAutoFlow
    | undefined;
  /** Omission uses a default for replacement and preserves on update; null stores Taffy None. */ gridTemplateAreas?:
    | GridTemplateAreasInput
    | null
    | undefined;
  /** Supplies the complete Grid template column-name list when present. */ gridTemplateColumnNames?:
    | readonly (readonly string[])[]
    | undefined;
  /** Supplies the complete Grid template row-name list when present. */ gridTemplateRowNames?:
    | readonly (readonly string[])[]
    | undefined;
  /** Supplies the node's Grid row placement when present. */ gridRow?:
    | PartialLineInput<GridPlacementInput>
    | undefined;
  /** Supplies the node's Grid column placement when present. */ gridColumn?:
    | PartialLineInput<GridPlacementInput>
    | undefined;
}

/** Supplies style fields to update; omitted or undefined fields and geometry components are preserved. */
export type StyleUpdate = StyleInput;

export function withEncodedStyle<T>(style: StyleInput, use: (encoded: Uint8Array) => T): T {
  return withStyleEncoder(style, 2, 6, (encoder) => {
    const display = style.display;
    if (display !== undefined) {
      encoder.field(0);
      const value = display;
      encoder.enumeration(value, 31, "Style.display");
    }
    const itemIsTable = style.itemIsTable;
    if (itemIsTable !== undefined) {
      encoder.field(1);
      const value = itemIsTable;
      encoder.boolean(value, "Style.itemIsTable");
    }
    const itemIsReplaced = style.itemIsReplaced;
    if (itemIsReplaced !== undefined) {
      encoder.field(2);
      const value = itemIsReplaced;
      encoder.boolean(value, "Style.itemIsReplaced");
    }
    const boxSizing = style.boxSizing;
    if (boxSizing !== undefined) {
      encoder.field(3);
      const value = boxSizing;
      encoder.enumeration(value, 3, "Style.boxSizing");
    }
    const direction = style.direction;
    if (direction !== undefined) {
      encoder.field(4);
      const value = direction;
      encoder.enumeration(value, 3, "Style.direction");
    }
    const overflow = style.overflow;
    if (overflow !== undefined) {
      encoder.field(5);
      const value = overflow;
      encoder.partialPointEnumeration(value, 15, "Style.overflow");
    }
    const scrollbarWidth = style.scrollbarWidth;
    if (scrollbarWidth !== undefined) {
      encoder.field(6);
      const value = scrollbarWidth;
      encoder.number(value, "Style.scrollbarWidth");
    }
    const contain = style.contain;
    if (contain !== undefined) {
      encoder.field(7);
      const value = contain;
      encoder.enumeration(value, 15, "Style.contain");
    }
    const float = style.float;
    if (float !== undefined) {
      encoder.field(8);
      const value = float;
      encoder.enumeration(value, 7, "Style.float");
    }
    const clear = style.clear;
    if (clear !== undefined) {
      encoder.field(9);
      const value = clear;
      encoder.enumeration(value, 15, "Style.clear");
    }
    const position = style.position;
    if (position !== undefined) {
      encoder.field(10);
      const value = position;
      encoder.enumeration(value, 3, "Style.position");
    }
    const inset = style.inset;
    if (inset !== undefined) {
      encoder.field(11);
      const value = inset;
      encoder.partialRectLengthPercentageAuto(value, "Style.inset");
    }
    const size = style.size;
    if (size !== undefined) {
      encoder.field(12);
      const value = size;
      encoder.partialSizeDimension(value, "Style.size");
    }
    const minSize = style.minSize;
    if (minSize !== undefined) {
      encoder.field(13);
      const value = minSize;
      encoder.partialSizeDimension(value, "Style.minSize");
    }
    const maxSize = style.maxSize;
    if (maxSize !== undefined) {
      encoder.field(14);
      const value = maxSize;
      encoder.partialSizeDimension(value, "Style.maxSize");
    }
    const aspectRatio = style.aspectRatio;
    if (aspectRatio !== undefined) {
      encoder.field(15);
      const value = aspectRatio;
      encoder.nullableNumber(value, "Style.aspectRatio");
    }
    const margin = style.margin;
    if (margin !== undefined) {
      encoder.field(16);
      const value = margin;
      encoder.partialRectLengthPercentageAuto(value, "Style.margin");
    }
    const padding = style.padding;
    if (padding !== undefined) {
      encoder.field(17);
      const value = padding;
      encoder.partialRectLengthPercentage(value, "Style.padding");
    }
    const border = style.border;
    if (border !== undefined) {
      encoder.field(18);
      const value = border;
      encoder.partialRectLengthPercentage(value, "Style.border");
    }
    const alignItems = style.alignItems;
    if (alignItems !== undefined) {
      encoder.field(19);
      const value = alignItems;
      encoder.nullableEnumeration(value, 65535, "Style.alignItems");
    }
    const alignSelf = style.alignSelf;
    if (alignSelf !== undefined) {
      encoder.field(20);
      const value = alignSelf;
      encoder.nullableEnumeration(value, 65535, "Style.alignSelf");
    }
    const justifyItems = style.justifyItems;
    if (justifyItems !== undefined) {
      encoder.field(21);
      const value = justifyItems;
      encoder.nullableEnumeration(value, 65535, "Style.justifyItems");
    }
    const justifySelf = style.justifySelf;
    if (justifySelf !== undefined) {
      encoder.field(22);
      const value = justifySelf;
      encoder.nullableEnumeration(value, 65535, "Style.justifySelf");
    }
    const alignContent = style.alignContent;
    if (alignContent !== undefined) {
      encoder.field(23);
      const value = alignContent;
      encoder.nullableEnumeration(value, 16383, "Style.alignContent");
    }
    const justifyContent = style.justifyContent;
    if (justifyContent !== undefined) {
      encoder.field(24);
      const value = justifyContent;
      encoder.nullableEnumeration(value, 16383, "Style.justifyContent");
    }
    const gap = style.gap;
    if (gap !== undefined) {
      encoder.field(25);
      const value = gap;
      encoder.partialSizeLengthPercentage(value, "Style.gap");
    }
    const textAlign = style.textAlign;
    if (textAlign !== undefined) {
      encoder.field(26);
      const value = textAlign;
      encoder.enumeration(value, 15, "Style.textAlign");
    }
    const flexDirection = style.flexDirection;
    if (flexDirection !== undefined) {
      encoder.field(27);
      const value = flexDirection;
      encoder.enumeration(value, 15, "Style.flexDirection");
    }
    const flexWrap = style.flexWrap;
    if (flexWrap !== undefined) {
      encoder.field(28);
      const value = flexWrap;
      encoder.enumeration(value, 7, "Style.flexWrap");
    }
    const flexBasis = style.flexBasis;
    if (flexBasis !== undefined) {
      encoder.field(29);
      const value = flexBasis;
      encoder.dimension(value, "Style.flexBasis");
    }
    const flexGrow = style.flexGrow;
    if (flexGrow !== undefined) {
      encoder.field(30);
      const value = flexGrow;
      encoder.number(value, "Style.flexGrow");
    }
    const flexShrink = style.flexShrink;
    if (flexShrink !== undefined) {
      encoder.field(31);
      const value = flexShrink;
      encoder.number(value, "Style.flexShrink");
    }
    const gridTemplateRows = style.gridTemplateRows;
    if (gridTemplateRows !== undefined) {
      encoder.field(32);
      const value = gridTemplateRows;
      encoder.gridTemplateComponents(value, "Style.gridTemplateRows");
    }
    const gridTemplateColumns = style.gridTemplateColumns;
    if (gridTemplateColumns !== undefined) {
      encoder.field(33);
      const value = gridTemplateColumns;
      encoder.gridTemplateComponents(value, "Style.gridTemplateColumns");
    }
    const gridAutoRows = style.gridAutoRows;
    if (gridAutoRows !== undefined) {
      encoder.field(34);
      const value = gridAutoRows;
      encoder.trackSizingFunctions(value, "Style.gridAutoRows");
    }
    const gridAutoColumns = style.gridAutoColumns;
    if (gridAutoColumns !== undefined) {
      encoder.field(35);
      const value = gridAutoColumns;
      encoder.trackSizingFunctions(value, "Style.gridAutoColumns");
    }
    const gridAutoFlow = style.gridAutoFlow;
    if (gridAutoFlow !== undefined) {
      encoder.field(36);
      const value = gridAutoFlow;
      encoder.enumeration(value, 15, "Style.gridAutoFlow");
    }
    const gridTemplateAreas = style.gridTemplateAreas;
    if (gridTemplateAreas !== undefined) {
      encoder.field(37);
      const value = gridTemplateAreas;
      encoder.nullableGridTemplateAreas(value, "Style.gridTemplateAreas");
    }
    const gridTemplateColumnNames = style.gridTemplateColumnNames;
    if (gridTemplateColumnNames !== undefined) {
      encoder.field(38);
      const value = gridTemplateColumnNames;
      encoder.stringMatrix(value, "Style.gridTemplateColumnNames");
    }
    const gridTemplateRowNames = style.gridTemplateRowNames;
    if (gridTemplateRowNames !== undefined) {
      encoder.field(39);
      const value = gridTemplateRowNames;
      encoder.stringMatrix(value, "Style.gridTemplateRowNames");
    }
    const gridRow = style.gridRow;
    if (gridRow !== undefined) {
      encoder.field(40);
      const value = gridRow;
      encoder.partialLineGridPlacement(value, "Style.gridRow");
    }
    const gridColumn = style.gridColumn;
    if (gridColumn !== undefined) {
      encoder.field(41);
      const value = gridColumn;
      encoder.partialLineGridPlacement(value, "Style.gridColumn");
    }
    return use(encoder.finish());
  });
}
