// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/numeric-families.json, api/tagged-values.json
// Regenerate: vp run codegen

import { AvailableSpaceKind, LengthUnit } from "./numeric-families.js";

/** Supplies the complete `Dimension.Length(value)` input form. */
export type LengthInput = {
  /** Selects the Length branch. */ unit: typeof LengthUnit.Length;
  /** Supplies the numeric payload for `Dimension.Length(value)`. */ value: number;
};

/** Supplies the complete `Dimension.Percent(value)` input form. */
export type PercentInput = {
  /** Selects the Percent branch. */ unit: typeof LengthUnit.Percent;
  /** Supplies the numeric payload for `Dimension.Percent(value)`. */ value: number;
};

/** Supplies the complete `Dimension.Auto` input form. */
export type AutoInput = {
  /** Selects the Auto branch. */ unit: typeof LengthUnit.Auto;
};

/** Supplies the complete `Dimension.MinContent` input form. */
type DimensionMinContentInput = {
  /** Selects the MinContent branch. */ unit: typeof LengthUnit.MinContent;
};

/** Supplies the complete `Dimension.MaxContent` input form. */
type DimensionMaxContentInput = {
  /** Selects the MaxContent branch. */ unit: typeof LengthUnit.MaxContent;
};

/** Supplies the complete `Dimension.FitContent` input form. */
type DimensionFitContentInput = {
  /** Selects the FitContent branch. */ unit: typeof LengthUnit.FitContent;
};

/** Supplies the complete `Dimension.FitContentLength(value)` input form. */
type DimensionFitContentLengthInput = {
  /** Selects the FitContentLength branch. */ unit: typeof LengthUnit.FitContentLength;
  /** Supplies the numeric payload for `Dimension.FitContentLength(value)`. */ value: number;
};

/** Supplies the complete `Dimension.FitContentPercent(value)` input form. */
type DimensionFitContentPercentInput = {
  /** Selects the FitContentPercent branch. */ unit: typeof LengthUnit.FitContentPercent;
  /** Supplies the numeric payload for `Dimension.FitContentPercent(value)`. */ value: number;
};

/** Supplies the complete `Dimension.Stretch` input form. */
type DimensionStretchInput = {
  /** Selects the Stretch branch. */ unit: typeof LengthUnit.Stretch;
};

/** Supplies the complete `Dimension.Content` input form. */
type DimensionContentInput = {
  /** Selects the Content branch. */ unit: typeof LengthUnit.Content;
};

/** Accepts a number as shorthand for `Dimension.Length(value)`, or a complete tagged `LengthPercentageInput` value. */
export type LengthPercentageInput = number | LengthInput | PercentInput;

/** Represents a complete tagged `LengthPercentage` value returned by the binding. */
export type LengthPercentage = Readonly<LengthInput> | Readonly<PercentInput>;

/** Accepts a number as shorthand for `Dimension.Length(value)`, or a complete tagged `LengthPercentageAutoInput` value. */
export type LengthPercentageAutoInput = number | LengthInput | PercentInput | AutoInput;

/** Represents a complete tagged `LengthPercentageAuto` value returned by the binding. */
export type LengthPercentageAuto =
  | Readonly<LengthInput>
  | Readonly<PercentInput>
  | Readonly<AutoInput>;

/** Accepts a number as shorthand for `Dimension.Length(value)`, or a complete tagged `DimensionInput` value. */
export type DimensionInput =
  | number
  | LengthInput
  | PercentInput
  | AutoInput
  | DimensionMinContentInput
  | DimensionMaxContentInput
  | DimensionFitContentInput
  | DimensionFitContentLengthInput
  | DimensionFitContentPercentInput
  | DimensionStretchInput
  | DimensionContentInput;

/** Represents a complete tagged `Dimension` value returned by the binding. */
export type Dimension =
  | Readonly<LengthInput>
  | Readonly<PercentInput>
  | Readonly<AutoInput>
  | Readonly<DimensionMinContentInput>
  | Readonly<DimensionMaxContentInput>
  | Readonly<DimensionFitContentInput>
  | Readonly<DimensionFitContentLengthInput>
  | Readonly<DimensionFitContentPercentInput>
  | Readonly<DimensionStretchInput>
  | Readonly<DimensionContentInput>;

const dimensionAuto = Object.freeze({ unit: LengthUnit.Auto } as const);

const dimensionMinContent = Object.freeze({ unit: LengthUnit.MinContent } as const);

const dimensionMaxContent = Object.freeze({ unit: LengthUnit.MaxContent } as const);

const dimensionFitContent = Object.freeze({ unit: LengthUnit.FitContent } as const);

const dimensionStretch = Object.freeze({ unit: LengthUnit.Stretch } as const);

const dimensionContent = Object.freeze({ unit: LengthUnit.Content } as const);

/** Provides complete tagged forms for dimension inputs, including `Dimension.Length(value)`, the form represented by numeric shorthand. */
export const Dimension = Object.freeze({
  Length(value: number): LengthInput {
    return { unit: LengthUnit.Length, value };
  },
  Percent(value: number): PercentInput {
    return { unit: LengthUnit.Percent, value };
  },
  Auto: dimensionAuto,
  MinContent: dimensionMinContent,
  MaxContent: dimensionMaxContent,
  FitContent: dimensionFitContent,
  FitContentLength(value: number): DimensionFitContentLengthInput {
    return { unit: LengthUnit.FitContentLength, value };
  },
  FitContentPercent(value: number): DimensionFitContentPercentInput {
    return { unit: LengthUnit.FitContentPercent, value };
  },
  Stretch: dimensionStretch,
  Content: dimensionContent,
});

/** Supplies the complete `AvailableSpace.Definite(value)` input form. */
type AvailableSpaceDefiniteInput = {
  /** Selects the Definite branch. */ kind: typeof AvailableSpaceKind.Definite;
  /** Supplies the numeric payload for `AvailableSpace.Definite(value)`. */ value: number;
};

/** Supplies the complete `AvailableSpace.MinContent` input form. */
type AvailableSpaceMinContentInput = {
  /** Selects the MinContent branch. */ kind: typeof AvailableSpaceKind.MinContent;
};

/** Supplies the complete `AvailableSpace.MaxContent` input form. */
type AvailableSpaceMaxContentInput = {
  /** Selects the MaxContent branch. */ kind: typeof AvailableSpaceKind.MaxContent;
};

/** Accepts a number as shorthand for `AvailableSpace.Definite(value)`, or a complete tagged `AvailableSpaceInput` value. */
export type AvailableSpaceInput =
  | number
  | AvailableSpaceDefiniteInput
  | AvailableSpaceMinContentInput
  | AvailableSpaceMaxContentInput;

/** Represents a complete tagged `AvailableSpace` value returned by the binding. */
export type AvailableSpace =
  | Readonly<AvailableSpaceDefiniteInput>
  | Readonly<AvailableSpaceMinContentInput>
  | Readonly<AvailableSpaceMaxContentInput>;

const availableSpaceMinContent = Object.freeze({ kind: AvailableSpaceKind.MinContent } as const);

const availableSpaceMaxContent = Object.freeze({ kind: AvailableSpaceKind.MaxContent } as const);

/** Provides complete tagged forms for available space inputs, including `AvailableSpace.Definite(value)`, the form represented by numeric shorthand. */
export const AvailableSpace = Object.freeze({
  Definite(value: number): AvailableSpaceDefiniteInput {
    return { kind: AvailableSpaceKind.Definite, value };
  },
  MinContent: availableSpaceMinContent,
  MaxContent: availableSpaceMaxContent,
});
