// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/numeric-families.json, api/tagged-values.json
// Regenerate: vp run codegen

import { AvailableSpaceKind, LengthUnit } from "./numeric-families.js";

/** Supplies the complete `Dimension.Length(value)` input form. */
export type LengthInput = {
  /** Selects the Length branch. */ unit: typeof LengthUnit.Length;
  /** Supplies the numeric payload for `Dimension.Length(value)`. */ value: number;
};

/** Supplies the complete `Dimension.Percent(value)` input form. */
export type PercentInput = {
  /** Selects the Percent branch. */ unit: typeof LengthUnit.Percent;
  /** Supplies the numeric payload for `Dimension.Percent(value)`. */ value: number;
};

/** Supplies the complete `Dimension.Auto` input form. */
export type AutoInput = {
  /** Selects the Auto branch. */ unit: typeof LengthUnit.Auto;
};

/** Accepts a number as shorthand for `Dimension.Length(value)`, or a complete tagged `LengthPercentageInput` value. */
export type LengthPercentageInput = number | LengthInput | PercentInput;

/** Represents a complete tagged `LengthPercentage` value returned by the binding. */
export type LengthPercentage = Readonly<LengthInput> | Readonly<PercentInput>;

/** Accepts a number as shorthand for `Dimension.Length(value)`, or a complete tagged `LengthPercentageAutoInput` value. */
export type LengthPercentageAutoInput = number | LengthInput | PercentInput | AutoInput;

/** Represents a complete tagged `LengthPercentageAuto` value returned by the binding. */
export type LengthPercentageAuto =
  | Readonly<LengthInput>
  | Readonly<PercentInput>
  | Readonly<AutoInput>;

/** Accepts a number as shorthand for `Dimension.Length(value)`, or a complete tagged `DimensionInput` value. */
export type DimensionInput = number | LengthInput | PercentInput | AutoInput;

/** Represents a complete tagged `Dimension` value returned by the binding. */
export type Dimension = Readonly<LengthInput> | Readonly<PercentInput> | Readonly<AutoInput>;

const dimensionAuto = Object.freeze({ unit: LengthUnit.Auto } as const);

/** Provides complete tagged forms for dimension inputs, including `Dimension.Length(value)`, the form represented by numeric shorthand. */
export const Dimension = Object.freeze({
  Length(value: number): LengthInput {
    return { unit: LengthUnit.Length, value };
  },
  Percent(value: number): PercentInput {
    return { unit: LengthUnit.Percent, value };
  },
  Auto: dimensionAuto,
});

/** Supplies the complete `AvailableSpace.Definite(value)` input form. */
type AvailableSpaceDefiniteInput = {
  /** Selects the Definite branch. */ kind: typeof AvailableSpaceKind.Definite;
  /** Supplies the numeric payload for `AvailableSpace.Definite(value)`. */ value: number;
};

/** Supplies the complete `AvailableSpace.MinContent` input form. */
type AvailableSpaceMinContentInput = {
  /** Selects the MinContent branch. */ kind: typeof AvailableSpaceKind.MinContent;
};

/** Supplies the complete `AvailableSpace.MaxContent` input form. */
type AvailableSpaceMaxContentInput = {
  /** Selects the MaxContent branch. */ kind: typeof AvailableSpaceKind.MaxContent;
};

/** Accepts a number as shorthand for `AvailableSpace.Definite(value)`, or a complete tagged `AvailableSpaceInput` value. */
export type AvailableSpaceInput =
  | number
  | AvailableSpaceDefiniteInput
  | AvailableSpaceMinContentInput
  | AvailableSpaceMaxContentInput;

/** Represents a complete tagged `AvailableSpace` value returned by the binding. */
export type AvailableSpace =
  | Readonly<AvailableSpaceDefiniteInput>
  | Readonly<AvailableSpaceMinContentInput>
  | Readonly<AvailableSpaceMaxContentInput>;

const availableSpaceMinContent = Object.freeze({ kind: AvailableSpaceKind.MinContent } as const);

const availableSpaceMaxContent = Object.freeze({ kind: AvailableSpaceKind.MaxContent } as const);

/** Provides complete tagged forms for available space inputs, including `AvailableSpace.Definite(value)`, the form represented by numeric shorthand. */
export const AvailableSpace = Object.freeze({
  Definite(value: number): AvailableSpaceDefiniteInput {
    return { kind: AvailableSpaceKind.Definite, value };
  },
  MinContent: availableSpaceMinContent,
  MaxContent: availableSpaceMaxContent,
});
