import type { NumericFamiliesModel } from "../../compiler/numeric-families.ts";
import type { OutputFile } from "../../index.ts";

export function emitNumericFamiliesRust(model: NumericFamiliesModel): OutputFile {
  const lines = [
    "// Code generated by tools/api-codegen. DO NOT EDIT.",
    "// Sources: api/numeric-families.json",
    "// Regenerate: vp run codegen",
    "",
    "macro_rules! numeric_codes {",
    "    (",
    "        $(",
    "            enum $name:ident {",
    "                $($variant:ident = $value:literal),+ $(,)?",
    "            }",
    "        )+",
    "    ) => {",
    "        $(",
    "            #[allow(dead_code)]",
    "            #[derive(Clone, Copy, Debug, Eq, PartialEq)]",
    "            #[repr(u8)]",
    "            pub(crate) enum $name {",
    "                $($variant = $value),+",
    "            }",
    "",
    "            impl TryFrom<i64> for $name {",
    "                type Error = ();",
    "",
    "                fn try_from(value: i64) -> Result<Self, Self::Error> {",
    "                    match value {",
    "                        $($value => Ok(Self::$variant)),+,",
    "                        _ => Err(()),",
    "                    }",
    "                }",
    "            }",
    "        )+",
    "    };",
    "}",
    "",
    "numeric_codes! {",
  ];

  for (const family of model.families) {
    lines.push(`    enum ${family.rustName} {`);
    for (const member of family.members) lines.push(`        ${member.name} = ${member.value},`);
    lines.push("    }");
  }
  lines.push("}");

  return { path: "crates/taffyjs_binding/src/numeric.rs", content: lines.join("\n") };
}
