import type { NumericFamiliesModel } from "../../compiler/numeric-families.ts";
import type { OutputFile } from "../../index.ts";

export function emitNumericFamiliesTypeScript(model: NumericFamiliesModel): OutputFile {
  const lines = [
    "// Code generated by tools/api-codegen. DO NOT EDIT.",
    "// Sources: api/numeric-families.json",
    "// Regenerate: vp run codegen",
    "",
    "/** Numeric constants shared by public JavaScript values and the native conversion layer. */",
    "export type EnumValue<Family extends Readonly<Record<string, number>>> = Family[keyof Family];",
  ];

  for (const family of model.families) {
    lines.push(
      "",
      `/** Lists the supported ${family.label} choices as stable numeric constants. */`,
      `export const ${family.name} = Object.freeze({`,
    );
    for (const member of family.members) {
      lines.push(
        `  /** Selects the ${member.name} choice from the ${family.name} numeric family. */`,
        `  ${member.name}: ${member.value},`,
      );
    }
    lines.push(
      "} as const);",
      "",
      `export type ${family.name} = EnumValue<typeof ${family.name}>;`,
    );
  }

  return {
    path: "packages/taffyjs-node/src/numeric-families.ts",
    content: lines.join("\n"),
  };
}
