import type { LayoutCodecModel } from "../../compiler/layout-codec.ts";
import type { OutputFile } from "../../index.ts";

export function emitLayoutCodecRust(model: LayoutCodecModel): OutputFile {
  const lines = [
    "// Code generated by tools/api-codegen. DO NOT EDIT.",
    "// Sources: api/layout-codec.json",
    "// Regenerate: vp run codegen",
    "",
    "use taffy::Layout;",
    "",
    `pub(crate) const OUTPUT_LENGTH: usize = ${model.slots.length};`,
  ];
  for (const slot of model.slots) {
    lines.push(`pub(crate) const ${slot.constantName}: usize = ${slot.index};`);
  }
  lines.push("", "pub(crate) fn write_output(value: &Layout, output: &mut [f64; OUTPUT_LENGTH]) {");
  for (const slot of model.slots) {
    lines.push(`    output[${slot.constantName}] = f64::from(value.${slot.rustPath});`);
  }
  lines.push("}");
  return {
    path: "crates/taffyjs_binding/src/layout_codec.rs",
    content: lines.join("\n"),
  };
}
