import type { LayoutField, LayoutCodecModel } from "../../compiler/layout-codec.ts";
import type { OutputFile } from "../../index.ts";

function slotConstant(model: LayoutCodecModel, path: string): string {
  const slot = model.slots.find((candidate) => candidate.typescriptPath === path);
  if (slot === undefined) throw new Error(`Missing compiled Layout slot for ${path}`);
  return slot.constantName;
}

function emitDecodedField(lines: string[], model: LayoutCodecModel, field: LayoutField): void {
  if (field.components.length === 0) {
    lines.push(`    ${field.name}: output[${slotConstant(model, field.name)}],`);
    return;
  }
  lines.push(`    ${field.name}: {`);
  for (const component of field.components) {
    lines.push(
      `      ${component.name}: output[${slotConstant(model, `${field.name}.${component.name}`)}],`,
    );
  }
  lines.push("    },");
}

export function emitLayoutCodecTypeScript(model: LayoutCodecModel): OutputFile {
  const importedTypes = [
    ...new Set(model.fields.map((field) => field.typeName.match(/^\w+/u)?.[0])),
  ]
    .filter((name): name is string => name !== undefined && name !== "number")
    .toSorted();
  const lines = [
    "// Code generated by tools/api-codegen. DO NOT EDIT.",
    "// Sources: api/layout-codec.json",
    "// Regenerate: vp run codegen",
    "",
    `import type { ${importedTypes.join(", ")} } from "./public-types.js";`,
    "",
    "/** Returns a detached readonly snapshot of a node's most recently stored layout. */",
    "export interface Layout {",
  ];
  for (const field of model.fields) {
    lines.push(`  /** ${field.documentation} */ readonly ${field.name}: ${field.typeName};`);
  }
  lines.push("}", "");
  for (const slot of model.slots) {
    lines.push(`const ${slot.constantName} = ${slot.index};`);
  }
  lines.push(
    "",
    `export const layoutCodecLength = ${model.slots.length};`,
    `export const layoutCodecByteLength = ${model.byteLength};`,
    "",
    "export function decodeLayout(output: Float64Array): Layout {",
    "  return {",
  );
  for (const field of model.fields) emitDecodedField(lines, model, field);
  lines.push("  };", "}");
  return {
    path: "packages/taffyjs-node/src/layout-codec.ts",
    content: lines.join("\n"),
  };
}
