import type { StyleField, StyleTransportModel } from "../../compiler/style-transport.ts";
import type { OutputFile } from "../../index.ts";

function enumParser(field: StyleField): string {
  const family = field.numericFamily;
  if (family === undefined) throw new Error(`Missing numeric family for ${field.name}`);
  return family.name
    .replace(/([A-Z]+)([A-Z][a-z])/gu, "$1_$2")
    .replace(/([a-z0-9])([A-Z])/gu, "$1_$2")
    .toLowerCase();
}

function replacement(
  functionName: string,
  target: string,
  value: string,
  forceMultiline = false,
): readonly string[] {
  const line = `changed |= ${functionName}(&mut ${target}, ${value});`;
  if (!forceMultiline && line.length <= 92) return [line];
  return [`changed |= ${functionName}(`, `    &mut ${target},`, `    ${value},`, ");"];
}

function fieldUpdate(field: StyleField): readonly string[] {
  const target = `target.${field.rustName}`;
  const name = JSON.stringify(`Style.${field.name}`);
  switch (field.category) {
    case "boolean":
      return replacement("replace", target, `decoder.boolean(${name})?`, true);
    case "number":
      return replacement("replace_f32", target, `decoder.number(${name})?`);
    case "nullable-number":
      return replacement("replace_optional_f32", target, `decoder.nullable_number(${name})?`);
    case "enum":
      return [
        `let value = style::${enumParser(field)}(f64::from(decoder.enumeration(${name})?))?;`,
        `changed |= replace(&mut ${target}, value);`,
      ];
    case "nullable-enum":
      return [
        "let value = decoder",
        `    .nullable_enumeration(${name})?`,
        `    .map(|value| style::${enumParser(field)}(f64::from(value)))`,
        "    .transpose()?;",
        `changed |= replace(&mut ${target}, value);`,
      ];
    case "partial-point-enum":
      return [`changed |= decoder.overflow(&mut ${target}, ${name})?;`];
    case "partial-rect-length-percentage-auto":
      return [`changed |= decoder.length_percentage_auto_rect(&mut ${target}, ${name})?;`];
    case "partial-size-dimension":
      return [`changed |= decoder.dimension_size(&mut ${target}, ${name})?;`];
    case "partial-rect-length-percentage":
      return [`changed |= decoder.length_percentage_rect(&mut ${target}, ${name})?;`];
    case "partial-size-length-percentage":
      return [`changed |= decoder.length_percentage_size(&mut ${target}, ${name})?;`];
    case "dimension":
      return replacement("replace", target, `decoder.dimension(${name})?`, true);
    case "grid-template-component-array":
      return replacement("replace", target, `decoder.grid_template_components(${name})?`);
    case "track-sizing-array":
      return replacement("replace", target, `decoder.track_sizing_functions(${name})?`);
    case "nullable-grid-template-areas":
      return replacement("replace", target, `decoder.nullable_grid_template_areas(${name})?`);
    case "string-matrix":
      return replacement("replace", target, `decoder.string_matrix(${name})?`);
    case "partial-line-grid-placement":
      return [`changed |= decoder.grid_placement_line(&mut ${target}, ${name})?;`];
  }
}

function emitField(lines: string[], field: StyleField): void {
  lines.push(`    if decoder.field(${field.index}) {`);
  for (const line of fieldUpdate(field)) lines.push(`        ${line}`);
  lines.push("    }");
}

export function emitStyleTransportRust(model: StyleTransportModel): OutputFile {
  const lines = [
    "// Code generated by tools/api-codegen. DO NOT EDIT.",
    "// Sources: api/numeric-families.json, api/style-transport.json",
    "// Regenerate: vp run codegen",
    "",
    "use taffy::style::Style;",
    "",
    "use crate::error::BindingResult;",
    "use crate::style;",
    "use crate::style_transport::{StyleDecoder, replace, replace_f32, replace_optional_f32};",
    "",
    "pub(crate) fn decode_into(target: &mut Style, encoded: &[u8]) -> BindingResult<bool> {",
    `    let mut decoder = StyleDecoder::new(encoded, ${model.wireVersion}, ${model.presenceBytes}, ${model.fields.length})?;`,
    "    let mut changed = false;",
  ];
  for (const field of model.fields) emitField(lines, field);
  lines.push("    decoder.finish()?;", "    style::validate(target)?;", "    Ok(changed)", "}");
  return {
    path: "crates/taffyjs_binding/src/style_input.rs",
    content: lines.join("\n"),
  };
}
