// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/layout-codec.json
// Regenerate: vp run codegen

use taffy::Layout;

pub(crate) const OUTPUT_LENGTH: usize = 23;
pub(crate) const ORDER_SLOT: usize = 0;
pub(crate) const LOCATION_X_SLOT: usize = 1;
pub(crate) const LOCATION_Y_SLOT: usize = 2;
pub(crate) const SIZE_WIDTH_SLOT: usize = 3;
pub(crate) const SIZE_HEIGHT_SLOT: usize = 4;
pub(crate) const SCROLLABLE_OVERFLOW_RECT_LEFT_SLOT: usize = 5;
pub(crate) const SCROLLABLE_OVERFLOW_RECT_RIGHT_SLOT: usize = 6;
pub(crate) const SCROLLABLE_OVERFLOW_RECT_TOP_SLOT: usize = 7;
pub(crate) const SCROLLABLE_OVERFLOW_RECT_BOTTOM_SLOT: usize = 8;
pub(crate) const SCROLLBAR_SIZE_WIDTH_SLOT: usize = 9;
pub(crate) const SCROLLBAR_SIZE_HEIGHT_SLOT: usize = 10;
pub(crate) const BORDER_LEFT_SLOT: usize = 11;
pub(crate) const BORDER_RIGHT_SLOT: usize = 12;
pub(crate) const BORDER_TOP_SLOT: usize = 13;
pub(crate) const BORDER_BOTTOM_SLOT: usize = 14;
pub(crate) const PADDING_LEFT_SLOT: usize = 15;
pub(crate) const PADDING_RIGHT_SLOT: usize = 16;
pub(crate) const PADDING_TOP_SLOT: usize = 17;
pub(crate) const PADDING_BOTTOM_SLOT: usize = 18;
pub(crate) const MARGIN_LEFT_SLOT: usize = 19;
pub(crate) const MARGIN_RIGHT_SLOT: usize = 20;
pub(crate) const MARGIN_TOP_SLOT: usize = 21;
pub(crate) const MARGIN_BOTTOM_SLOT: usize = 22;

pub(crate) fn write_output(value: &Layout, output: &mut [f64; OUTPUT_LENGTH]) {
    output[ORDER_SLOT] = f64::from(value.order);
    output[LOCATION_X_SLOT] = f64::from(value.location.x);
    output[LOCATION_Y_SLOT] = f64::from(value.location.y);
    output[SIZE_WIDTH_SLOT] = f64::from(value.size.width);
    output[SIZE_HEIGHT_SLOT] = f64::from(value.size.height);
    output[SCROLLABLE_OVERFLOW_RECT_LEFT_SLOT] = f64::from(value.scrollable_overflow_rect.left);
    output[SCROLLABLE_OVERFLOW_RECT_RIGHT_SLOT] = f64::from(value.scrollable_overflow_rect.right);
    output[SCROLLABLE_OVERFLOW_RECT_TOP_SLOT] = f64::from(value.scrollable_overflow_rect.top);
    output[SCROLLABLE_OVERFLOW_RECT_BOTTOM_SLOT] = f64::from(value.scrollable_overflow_rect.bottom);
    output[SCROLLBAR_SIZE_WIDTH_SLOT] = f64::from(value.scrollbar_size.width);
    output[SCROLLBAR_SIZE_HEIGHT_SLOT] = f64::from(value.scrollbar_size.height);
    output[BORDER_LEFT_SLOT] = f64::from(value.border.left);
    output[BORDER_RIGHT_SLOT] = f64::from(value.border.right);
    output[BORDER_TOP_SLOT] = f64::from(value.border.top);
    output[BORDER_BOTTOM_SLOT] = f64::from(value.border.bottom);
    output[PADDING_LEFT_SLOT] = f64::from(value.padding.left);
    output[PADDING_RIGHT_SLOT] = f64::from(value.padding.right);
    output[PADDING_TOP_SLOT] = f64::from(value.padding.top);
    output[PADDING_BOTTOM_SLOT] = f64::from(value.padding.bottom);
    output[MARGIN_LEFT_SLOT] = f64::from(value.margin.left);
    output[MARGIN_RIGHT_SLOT] = f64::from(value.margin.right);
    output[MARGIN_TOP_SLOT] = f64::from(value.margin.top);
    output[MARGIN_BOTTOM_SLOT] = f64::from(value.margin.bottom);
}
