// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/numeric-families.json, api/tagged-values.json
// Regenerate: vp run codegen

use napi::ValueType;
use napi::bindgen_prelude::Unknown;
use napi_derive::napi;

use crate::error::{NativeResult, type_error};
use crate::js_object;
use crate::number;
use crate::numeric::{AvailableSpaceKindCode, LengthUnitCode};

#[napi(object, object_to_js = false)]
pub struct DimensionTaggedInput {
    pub unit: f64,
    pub value: Option<f64>,
}

#[derive(Clone, Copy, Debug, PartialEq)]
enum DimensionTaggedValue {
    Length(f64),
    Percent(f64),
    Auto,
}

fn parse_dimension_tagged_value(
    value: Unknown<'_>,
    accepts_number: bool,
) -> NativeResult<DimensionTaggedValue> {
    if value
        .get_type()
        .map_err(|_| type_error("Could not inspect dimension input"))?
        == ValueType::Number
    {
        if !accepts_number {
            return Err(type_error("Expected a tagged dimension object"));
        }
        return Ok(DimensionTaggedValue::Length(number::from_unknown(
            value,
            "Dimension shorthand",
        )?));
    }

    let input: DimensionTaggedInput = js_object::input(value, "a tagged dimension object", None)?;
    let tag = number::to_integer::<LengthUnitCode>(input.unit)?;
    let parsed = match tag {
        LengthUnitCode::Length => {
            let payload = js_object::required(input.value, "Length value")?;
            DimensionTaggedValue::Length(payload)
        }
        LengthUnitCode::Percent => {
            let payload = js_object::required(input.value, "Percent value")?;
            DimensionTaggedValue::Percent(payload)
        }
        LengthUnitCode::Auto => DimensionTaggedValue::Auto,
    };
    Ok(parsed)
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum LengthPercentageInputValue {
    Length(f64),
    Percent(f64),
}

#[allow(dead_code)]
pub(crate) fn parse_length_percentage(
    value: Unknown<'_>,
) -> NativeResult<LengthPercentageInputValue> {
    let parsed = parse_dimension_tagged_value(value, true)?;
    Ok(match parsed {
        DimensionTaggedValue::Length(payload) => LengthPercentageInputValue::Length(payload),
        DimensionTaggedValue::Percent(payload) => LengthPercentageInputValue::Percent(payload),
        DimensionTaggedValue::Auto => {
            return Err(type_error("Auto is not valid for LengthPercentageInput"));
        }
    })
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum LengthPercentageAutoInputValue {
    Length(f64),
    Percent(f64),
    Auto,
}

#[allow(dead_code)]
pub(crate) fn parse_length_percentage_auto(
    value: Unknown<'_>,
) -> NativeResult<LengthPercentageAutoInputValue> {
    let parsed = parse_dimension_tagged_value(value, true)?;
    Ok(match parsed {
        DimensionTaggedValue::Length(payload) => LengthPercentageAutoInputValue::Length(payload),
        DimensionTaggedValue::Percent(payload) => LengthPercentageAutoInputValue::Percent(payload),
        DimensionTaggedValue::Auto => LengthPercentageAutoInputValue::Auto,
    })
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum DimensionInputValue {
    Length(f64),
    Percent(f64),
    Auto,
}

#[allow(dead_code)]
pub(crate) fn parse_dimension(value: Unknown<'_>) -> NativeResult<DimensionInputValue> {
    let parsed = parse_dimension_tagged_value(value, true)?;
    Ok(match parsed {
        DimensionTaggedValue::Length(payload) => DimensionInputValue::Length(payload),
        DimensionTaggedValue::Percent(payload) => DimensionInputValue::Percent(payload),
        DimensionTaggedValue::Auto => DimensionInputValue::Auto,
    })
}

#[napi(object, object_to_js = false)]
pub struct AvailableSpaceTaggedInput {
    pub kind: f64,
    pub value: Option<f64>,
}

#[derive(Clone, Copy, Debug, PartialEq)]
enum AvailableSpaceTaggedValue {
    Definite(f64),
    MinContent,
    MaxContent,
}

fn parse_available_space_tagged_value(
    value: Unknown<'_>,
    accepts_number: bool,
) -> NativeResult<AvailableSpaceTaggedValue> {
    if value
        .get_type()
        .map_err(|_| type_error("Could not inspect available space input"))?
        == ValueType::Number
    {
        if !accepts_number {
            return Err(type_error("Expected a tagged available space object"));
        }
        return Ok(AvailableSpaceTaggedValue::Definite(number::from_unknown(
            value,
            "AvailableSpace shorthand",
        )?));
    }

    let input: AvailableSpaceTaggedInput =
        js_object::input(value, "a tagged available space object", None)?;
    let tag = number::to_integer::<AvailableSpaceKindCode>(input.kind)?;
    let parsed = match tag {
        AvailableSpaceKindCode::Definite => {
            let payload = js_object::required(input.value, "Definite value")?;
            AvailableSpaceTaggedValue::Definite(payload)
        }
        AvailableSpaceKindCode::MinContent => AvailableSpaceTaggedValue::MinContent,
        AvailableSpaceKindCode::MaxContent => AvailableSpaceTaggedValue::MaxContent,
    };
    Ok(parsed)
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum AvailableSpaceInputValue {
    Definite(f64),
    MinContent,
    MaxContent,
}

#[allow(dead_code)]
pub(crate) fn parse_available_space(value: Unknown<'_>) -> NativeResult<AvailableSpaceInputValue> {
    let parsed = parse_available_space_tagged_value(value, true)?;
    Ok(match parsed {
        AvailableSpaceTaggedValue::Definite(payload) => AvailableSpaceInputValue::Definite(payload),
        AvailableSpaceTaggedValue::MinContent => AvailableSpaceInputValue::MinContent,
        AvailableSpaceTaggedValue::MaxContent => AvailableSpaceInputValue::MaxContent,
    })
}
