// Code generated by tools/api-codegen. DO NOT EDIT.
// Sources: api/numeric-families.json, api/tagged-values.json
// Regenerate: vp run codegen

use napi::ValueType;
use napi::bindgen_prelude::Unknown;
use napi_derive::napi;

use crate::error::{BindingResult, type_error};
use crate::js_object;
use crate::number;
use crate::numeric::AvailableSpaceKindCode;

#[napi(object, object_to_js = false)]
pub struct AvailableSpaceTaggedInput {
    pub kind: f64,
    pub value: Option<f64>,
}

#[derive(Clone, Copy, Debug, PartialEq)]
enum AvailableSpaceTaggedValue {
    Definite(f64),
    MinContent,
    MaxContent,
}

fn parse_available_space_tagged_value(
    value: Unknown<'_>,
    accepts_number: bool,
) -> BindingResult<AvailableSpaceTaggedValue> {
    if value
        .get_type()
        .map_err(|_| type_error("Could not inspect available space input"))?
        == ValueType::Number
    {
        if !accepts_number {
            return Err(type_error("Expected a tagged available space object"));
        }
        return Ok(AvailableSpaceTaggedValue::Definite(number::from_unknown(
            value,
            "AvailableSpace shorthand",
        )?));
    }

    let input: AvailableSpaceTaggedInput =
        js_object::input(value, "a tagged available space object", None)?;
    let tag = number::to_integer::<AvailableSpaceKindCode>(input.kind)?;
    let parsed = match tag {
        AvailableSpaceKindCode::Definite => {
            let payload = js_object::required(input.value, "Definite value")?;
            AvailableSpaceTaggedValue::Definite(payload)
        }
        AvailableSpaceKindCode::MinContent => AvailableSpaceTaggedValue::MinContent,
        AvailableSpaceKindCode::MaxContent => AvailableSpaceTaggedValue::MaxContent,
    };
    Ok(parsed)
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum AvailableSpaceInputValue {
    Definite(f64),
    MinContent,
    MaxContent,
}

pub(crate) fn parse_available_space(value: Unknown<'_>) -> BindingResult<AvailableSpaceInputValue> {
    let parsed = parse_available_space_tagged_value(value, true)?;
    Ok(match parsed {
        AvailableSpaceTaggedValue::Definite(payload) => AvailableSpaceInputValue::Definite(payload),
        AvailableSpaceTaggedValue::MinContent => AvailableSpaceInputValue::MinContent,
        AvailableSpaceTaggedValue::MaxContent => AvailableSpaceInputValue::MaxContent,
    })
}
