/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeTaffyTree {
  constructor();
  rawEnableRounding(): void;
  rawDisableRounding(): void;
  rawNodeCount(): number;
  rawChildCount(parent: bigint): number;
  rawParent(node: bigint): bigint | null;
  rawChildren(parent: bigint): Array<bigint>;
  rawChildAtIndex(parent: bigint, index: number): bigint;
  rawAddChild(parent: bigint, child: bigint): void;
  rawInsertChildAtIndex(parent: bigint, index: number, child: bigint): void;
  rawSetChildren(parent: bigint, children: Array<bigint>): void;
  rawRemoveChild(parent: bigint, child: bigint): void;
  rawRemoveChildAtIndex(parent: bigint, index: number): bigint;
  rawRemoveChildrenRange(parent: bigint, range: ChildRangeInput): void;
  rawReplaceChildAtIndex(parent: bigint, index: number, newChild: bigint): bigint;
  rawRemove(node: bigint): void;
  rawClear(): void;
  rawNewLeaf(style: unknown): bigint;
  rawNewLeafWithContext(style: unknown, hasContext: boolean): bigint;
  rawNewWithChildren(style: unknown, children: Array<bigint>): bigint;
  rawSetStyle(node: bigint, style: unknown): void;
  rawSetNodeContext(node: bigint, hasContext: boolean): void;
  rawGetStyle(node: bigint): StyleOutput;
  rawComputeLayout(node: bigint, availableSpace: unknown): void;
  rawGetLayout(node: bigint): LayoutOutput;
  rawGetUnroundedLayout(node: bigint): LayoutOutput;
  rawGetDetailedLayoutInfo(node: bigint): DetailedLayoutOutput;
  rawMarkDirty(node: bigint): void;
  rawIsDirty(node: bigint): boolean;
  rawComputeLayoutWithMeasure(
    node: bigint,
    availableSpace: unknown,
    measure: (arg: MeasureArguments) => unknown,
  ): void;
}

export interface AvailableSpaceOutput {
  kind: number;
  value?: number;
}

export interface AvailableSpaceSizeOutput {
  width: AvailableSpaceOutput;
  height: AvailableSpaceOutput;
}

export interface AvailableSpaceTaggedInput {
  kind: number;
  value?: number;
}

export interface ChildRangeInput {
  start: number;
  end: number;
}

export interface CompleteSizeInput {
  width: unknown;
  height: unknown;
}

export interface DetailedGridItemOutput {
  rowStart: number;
  rowEnd: number;
  columnStart: number;
  columnEnd: number;
}

export interface DetailedGridOutput {
  rows: DetailedGridTracksOutput;
  columns: DetailedGridTracksOutput;
  items: Array<DetailedGridItemOutput>;
}

export interface DetailedGridTracksOutput {
  negativeImplicitTracks: number;
  explicitTracks: number;
  positiveImplicitTracks: number;
  gutters: Array<number>;
  sizes: Array<number>;
}

export interface DetailedLayoutOutput {
  kind: number;
  value?: DetailedGridOutput;
}

export interface DimensionTaggedInput {
  unit: number;
  value?: number;
}

export interface GridPlacementInput {
  kind: number;
  name?: string;
  index?: number;
  span?: number;
}

export interface GridPlacementLineOutput {
  start: GridPlacementOutput;
  end: GridPlacementOutput;
}

export interface GridPlacementOutput {
  kind: number;
  name?: string;
  index?: number;
  span?: number;
}

export interface GridTemplateAreaInput {
  name: string;
  rowStart: number;
  rowEnd: number;
  columnStart: number;
  columnEnd: number;
}

export interface GridTemplateAreaOutput {
  name: string;
  rowStart: number;
  rowEnd: number;
  columnStart: number;
  columnEnd: number;
}

export interface GridTemplateAreasInput {
  areas: Array<GridTemplateAreaInput>;
  rowCount: number;
  columnCount: number;
}

export interface GridTemplateAreasOutput {
  areas: Array<GridTemplateAreaOutput>;
  rowCount: number;
  columnCount: number;
}

export interface GridTemplateComponentOutput {
  kind: number;
  value: TrackSizingOutput | GridTemplateRepetitionOutput;
}

export interface GridTemplateRepetitionInput {
  count: unknown;
  tracks: Array<unknown>;
  lineNames: Array<Array<string>>;
}

export interface GridTemplateRepetitionOutput {
  count: RepetitionCountOutput;
  tracks: Array<TrackSizingOutput>;
  lineNames: Array<Array<string>>;
}

export interface KnownDimensionsOutput {
  width: number | undefined;
  height: number | undefined;
}

export interface LayoutOutput {
  order: number;
  location: NumberPointOutput;
  size: NumberSizeOutput;
  contentSize: NumberSizeOutput;
  scrollbarSize: NumberSizeOutput;
  border: NumberRectOutput;
  padding: NumberRectOutput;
  margin: NumberRectOutput;
}

export interface LengthOutput {
  unit: number;
  value?: number;
}

export interface LengthRectOutput {
  left: LengthOutput;
  right: LengthOutput;
  top: LengthOutput;
  bottom: LengthOutput;
}

export interface LengthSizeOutput {
  width: LengthOutput;
  height: LengthOutput;
}

export interface MaybeTaggedLengthInput {
  unit?: number;
}

export interface MeasureArguments {
  knownDimensions: KnownDimensionsOutput;
  availableSpace: AvailableSpaceSizeOutput;
  node: bigint;
  style: StyleOutput;
}

export interface MeasureResultInput {
  width: number;
  height: number;
}

export interface NumberPointOutput {
  x: number;
  y: number;
}

export interface NumberRectOutput {
  left: number;
  right: number;
  top: number;
  bottom: number;
}

export interface NumberSizeOutput {
  width: number;
  height: number;
}

export interface OverflowOutput {
  x: number;
  y: number;
}

export interface PartialLineInput {
  start?: unknown;
  end?: unknown;
}

export interface PartialPointInput {
  x?: number;
  y?: number;
}

export interface PartialRectInput {
  left?: unknown;
  right?: unknown;
  top?: unknown;
  bottom?: unknown;
}

export interface PartialSizeInput {
  width?: unknown;
  height?: unknown;
}

export interface RepetitionCountOutput {
  kind: number;
  value?: number;
}

export interface StyleInput {
  display?: number;
  itemIsTable?: boolean;
  itemIsReplaced?: boolean;
  boxSizing?: number;
  direction?: number;
  overflow?: unknown;
  scrollbarWidth?: number;
  float?: number;
  clear?: number;
  position?: number;
  inset?: unknown;
  size?: unknown;
  minSize?: unknown;
  maxSize?: unknown;
  aspectRatio?: number | null;
  margin?: unknown;
  padding?: unknown;
  border?: unknown;
  alignItems?: number | null;
  alignSelf?: number | null;
  justifyItems?: number | null;
  justifySelf?: number | null;
  alignContent?: number | null;
  justifyContent?: number | null;
  gap?: unknown;
  textAlign?: number;
  flexDirection?: number;
  flexWrap?: number;
  flexBasis?: unknown;
  flexGrow?: number;
  flexShrink?: number;
  gridTemplateRows?: Array<unknown>;
  gridTemplateColumns?: Array<unknown>;
  gridAutoRows?: Array<unknown>;
  gridAutoColumns?: Array<unknown>;
  gridAutoFlow?: number;
  gridTemplateAreas?: GridTemplateAreasInput | null;
  gridTemplateColumnNames?: Array<Array<string>>;
  gridTemplateRowNames?: Array<Array<string>>;
  gridRow?: unknown;
  gridColumn?: unknown;
}

export interface StyleOutput {
  display: number;
  itemIsTable: boolean;
  itemIsReplaced: boolean;
  boxSizing: number;
  direction: number;
  overflow: OverflowOutput;
  scrollbarWidth: number;
  float: number;
  clear: number;
  position: number;
  inset: LengthRectOutput;
  size: LengthSizeOutput;
  minSize: LengthSizeOutput;
  maxSize: LengthSizeOutput;
  aspectRatio: number | null;
  margin: LengthRectOutput;
  padding: LengthRectOutput;
  border: LengthRectOutput;
  alignItems: number | null;
  alignSelf: number | null;
  justifyItems: number | null;
  justifySelf: number | null;
  alignContent: number | null;
  justifyContent: number | null;
  gap: LengthSizeOutput;
  textAlign: number;
  flexDirection: number;
  flexWrap: number;
  flexBasis: LengthOutput;
  flexGrow: number;
  flexShrink: number;
  gridTemplateRows: Array<GridTemplateComponentOutput>;
  gridTemplateColumns: Array<GridTemplateComponentOutput>;
  gridAutoRows: Array<TrackSizingOutput>;
  gridAutoColumns: Array<TrackSizingOutput>;
  gridAutoFlow: number;
  gridTemplateAreas: GridTemplateAreasOutput | null;
  gridTemplateColumnNames: Array<Array<string>>;
  gridTemplateRowNames: Array<Array<string>>;
  gridRow: GridPlacementLineOutput;
  gridColumn: GridPlacementLineOutput;
}

export interface TaggedGridInput {
  kind: number;
  value?: unknown;
}

export interface TrackSizingInput {
  min: unknown;
  max: unknown;
}

export interface TrackSizingOutput {
  min: TrackSizingValueOutput;
  max: TrackSizingValueOutput;
}

export interface TrackSizingValueOutput {
  kind: number;
  value?: number | LengthOutput;
}
