/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BindingTaffyTree {
  constructor();
  rawEnableRounding(): void;
  rawDisableRounding(): void;
  rawGetNodeCount(): number;
  rawGetChildCount(parent: bigint): number;
  rawGetParent(node: bigint): bigint | null;
  rawGetChildren(parent: bigint): Array<bigint>;
  rawGetChildAtIndex(parent: bigint, index: number): bigint;
  rawAddChild(parent: bigint, child: bigint): void;
  rawInsertChildAtIndex(parent: bigint, index: number, child: bigint): void;
  rawSetChildren(parent: bigint, children: Array<bigint>): void;
  rawRemoveChild(parent: bigint, child: bigint): void;
  rawRemoveChildAtIndex(parent: bigint, index: number): bigint;
  rawRemoveChildrenRange(parent: bigint, range: ChildRangeInput): void;
  rawReplaceChildAtIndex(parent: bigint, index: number, newChild: bigint): bigint;
  rawRemove(node: bigint): void;
  rawClear(): void;
  rawNewLeaf(encoded: Uint8Array): bigint;
  rawNewLeafWithContext(encoded: Uint8Array, hasContext: boolean): bigint;
  rawNewWithChildren(encoded: Uint8Array, children: Array<bigint>): bigint;
  rawSetStyle(node: bigint, encoded: Uint8Array): void;
  rawUpdateStyle(node: bigint, encoded: Uint8Array): void;
  rawSetNodeContext(node: bigint, hasContext: boolean): void;
  rawSetMeasure(node: bigint, hasMeasure: boolean): void;
  rawGetStyle(node: bigint): StyleOutput;
  rawComputeLayout(node: bigint, availableSpace: unknown): void;
  rawWriteLayout(node: bigint, output: Float64Array): void;
  rawWriteUnroundedLayout(node: bigint, output: Float64Array): void;
  rawGetDetailedLayoutInfo(node: bigint): DetailedLayoutOutput;
  rawMarkDirty(node: bigint): void;
  rawIsDirty(node: bigint): boolean;
  rawComputeLayoutWithMeasure(
    node: bigint,
    availableSpace: unknown,
    measure: (arg: unknown) => unknown,
    constraints: Float64Array,
    hasGlobalMeasure: boolean,
  ): void;
}

export interface AvailableSpaceTaggedInput {
  kind: number;
  value?: number;
}

export interface ChildRangeInput {
  start: number;
  end: number;
}

export interface CompleteSizeInput {
  width: unknown;
  height: unknown;
}

export interface DetailedGridItemOutput {
  rowStart: number;
  rowEnd: number;
  columnStart: number;
  columnEnd: number;
}

export interface DetailedGridOutput {
  rows: DetailedGridTracksOutput;
  columns: DetailedGridTracksOutput;
  items: Array<DetailedGridItemOutput>;
}

export interface DetailedGridTrackPositionOutput {
  start: number;
  end: number;
}

export interface DetailedGridTracksOutput {
  negativeImplicitTracks: number;
  explicitTracks: number;
  positiveImplicitTracks: number;
  positions: Array<DetailedGridTrackPositionOutput>;
  lineNames: Array<Array<string>>;
}

export interface DetailedLayoutOutput {
  kind: number;
  value?: DetailedGridOutput;
}

export interface GridPlacementLineOutput {
  start: GridPlacementOutput;
  end: GridPlacementOutput;
}

export interface GridPlacementOutput {
  kind: number;
  name?: string;
  index?: number;
  span?: number;
}

export interface GridTemplateAreaOutput {
  name: string;
  rowStart: number;
  rowEnd: number;
  columnStart: number;
  columnEnd: number;
}

export interface GridTemplateAreasOutput {
  areas: Array<GridTemplateAreaOutput>;
  rowCount: number;
  columnCount: number;
}

export interface GridTemplateComponentOutput {
  kind: number;
  value: TrackSizingOutput | GridTemplateRepetitionOutput;
}

export interface GridTemplateRepetitionOutput {
  count: RepetitionCountOutput;
  tracks: Array<TrackSizingOutput>;
  lineNames: Array<Array<string>>;
}

export interface LengthOutput {
  unit: number;
  value?: number;
}

export interface LengthRectOutput {
  left: LengthOutput;
  right: LengthOutput;
  top: LengthOutput;
  bottom: LengthOutput;
}

export interface LengthSizeOutput {
  width: LengthOutput;
  height: LengthOutput;
}

export interface MeasureResultInput {
  width: number;
  height: number;
}

export interface OverflowOutput {
  x: number;
  y: number;
}

export interface RepetitionCountOutput {
  kind: number;
  value?: number;
}

export interface StyleOutput {
  display: number;
  itemIsTable: boolean;
  itemIsReplaced: boolean;
  boxSizing: number;
  direction: number;
  overflow: OverflowOutput;
  scrollbarWidth: number;
  contain: number;
  float: number;
  clear: number;
  position: number;
  inset: LengthRectOutput;
  size: LengthSizeOutput;
  minSize: LengthSizeOutput;
  maxSize: LengthSizeOutput;
  aspectRatio: number | null;
  margin: LengthRectOutput;
  padding: LengthRectOutput;
  border: LengthRectOutput;
  alignItems: number | null;
  alignSelf: number | null;
  justifyItems: number | null;
  justifySelf: number | null;
  alignContent: number | null;
  justifyContent: number | null;
  gap: LengthSizeOutput;
  textAlign: number;
  flexDirection: number;
  flexWrap: number;
  flexBasis: LengthOutput;
  flexGrow: number;
  flexShrink: number;
  gridTemplateRows: Array<GridTemplateComponentOutput>;
  gridTemplateColumns: Array<GridTemplateComponentOutput>;
  gridAutoRows: Array<TrackSizingOutput>;
  gridAutoColumns: Array<TrackSizingOutput>;
  gridAutoFlow: number;
  gridTemplateAreas: GridTemplateAreasOutput | null;
  gridTemplateColumnNames: Array<Array<string>>;
  gridTemplateRowNames: Array<Array<string>>;
  gridRow: GridPlacementLineOutput;
  gridColumn: GridPlacementLineOutput;
}

export interface TrackSizingOutput {
  min: TrackSizingValueOutput;
  max: TrackSizingValueOutput;
}

export interface TrackSizingValueOutput {
  kind: number;
  value?: number | LengthOutput;
}
