/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeTaffyTree {
  constructor();
  rawNodeCount(publicMethod: string): number;
  rawChildCount(parent: bigint, publicMethod: string): number;
  rawParent(node: bigint, publicMethod: string): bigint | null;
  rawChildren(parent: bigint, publicMethod: string): Array<bigint>;
  rawClear(publicMethod: string): void;
  rawNewLeaf(style: unknown, publicMethod: string): bigint;
  rawNewWithChildren(style: unknown, children: Array<bigint>, publicMethod: string): bigint;
  rawSetStyle(node: bigint, style: unknown, publicMethod: string): void;
  rawGetStyle(node: bigint, publicMethod: string): object;
  rawComputeLayout(node: bigint, availableSpace: unknown, publicMethod: string): void;
  rawGetLayout(node: bigint, publicMethod: string): object;
  rawGetDetailedLayoutInfo(node: bigint, publicMethod: string): object;
  rawComputeLayoutWithMeasure(
    node: bigint,
    availableSpace: unknown,
    measure: (arg: object) => unknown,
    publicMethod: string,
  ): void;
}
